project:
  type: website
  output-dir: docs
website:
  site-url: http://joshfbaker.github.io/
  title: "Baker's Blog"
  description: "Baker's Blog"
  favicon: favicon.ico
  twitter-card: true
  open-graph: true

  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/joshua-baker-87111818/
      - icon: github
        href: https://github.com/joshfbaker
      - icon: rss
        href: index.xml
format:
  html:
    theme: flatly
    css: styles.css


