project:
  type: website
  output-dir: docs
website:
  title: "Baker's Blog"
  site-url: http://joshfbaker.github.io/
  description: "Baker's Blog"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/joshua-baker-87111818/
      - icon: github
        href: https://github.com/joshfbaker
      - icon: rss
        href: index.xml
    favicon: favicon.ico
    twitter-card: true
    open-graph: true
format:
  html:
    theme: flatly
    css: styles.css


